spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: Akshita@1308
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
  main:
    web-application-type: servlet
